# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--name", "mybox"]
  end

  config.vm.box = "windows2008R2"
  config.vm.guest = :windows


  config.vm.define "mybox" do |oi|
    oi.vm.network :private_network, ip: "10.10.200.200"
  end

  config.vm.communicator = "winrm"
  config.winrm.username = "vagrant"
  config.winrm.password = "vagrant"

  config.vm.provider "virtualbox" do |v|
    v.gui = true
    v.cpus = 2
    v.memory = 2048
  end

end